# https://medium.com/collaborne-engineering/how-to-build-polymer-components-with-github-and-travis-67683ef8bf0d
# https://github.com/Collaborne/d3-progress-meter/blob/master/.travis.yml

dist: trusty
sudo: false
group: beta

language: node_js
node_js:
- node
addons:
  firefox: latest-esr
cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"
before_install:
- "if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi"
before_script:
- npm install web-component-tester bower
# - npm install web-component-tester bower polylint
- $(npm bin)/bower install
# - $(npm bin)/polylint --no-recursion
script:
- xvfb-run $(npm bin)/wct
- npm run coverage
after_success: 'npm run coveralls'

# # Polymer 2.0, but does not work: 
# # ENOENT: no such file or directory, open '/home/travis/build/vladimirbrasil/a-timer/package.json'
# # https://github.com/Polymer/hn-polymer-2/blob/master/.travis.yml
# # polymer-cli   
# language: node_js
# sudo: required
# dist: trusty
# addons:
#   firefox: latest
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
# node_js: stable
# before_script:
#   - npm install -g bower polymer-cli
#   - bower install
# cache: yarn
# script:
#   - xvfb-run npm test
